# 山姆会员 Token
authToken: "<authToken>"
# 运行模式
# 1->山姆抢购 | 2->保供抢购
runMode: 1
# 保供抢购关键字黑白名单筛选
supplySet:
  # 是否开启
  isEnabled: false
  # 筛选方式
  # 1->白名单 | 2->黑名单
  mode: 1
  # 检测有以下关键字的内容，例：["蔬菜", "保供套餐C"]
  keyWords: ["<关键字>"]
# 运力暴力模式
bruteCapacity: true
# 设备类型模拟
# 1->IOS | 2->小程序
deviceType: 1
# 配送方式
# 1->极速达 | 2->全城配
deliveryType: 2
# 商店类型
# 2->生鲜直达 | 4->极速达 | 8->全球购保税
storeType: 2
# 商品类型
# 1->普通商品 | 2->全球购商品
floorId: 1
# 是否忽略无效商品
ignoreInvalid: true
# 自动修正限购商品数量
autoFixPurchaseLimit:
  # 是否开启
  isEnabled: true
  # 是否开启线下修正，只影响最后提交订单内容
  fixOffline: true
  # 是否开启线上修正，会影响线上购物车商品的数量
  fixOnline: false
# 运力搜索时间跨度（日）
perDateLen : 7
# SaasId 无需改动
saasId: "1818"
# 代理设置
proxySet:
  # 是否开启代理
  isEnabled: false
  # 代理 URL
  proxyUrl: "http://127.0.0.1:8080"

# 各步骤休眠时间（毫秒）
sleepTimeSet:
  stepStoreSleep: 1000
  stepCartSleep: 1000
  stepCartShowSleep: 1000
  stepGoodsSleep: 1000
  stepCapacitySleep: 1000
  stepOrderSleep: 100
  stepSupplySleep: 750

# 通知设置
noticeSet:
  # 通知类型
  # 0->不通知 | 1->Bark | 2->Server酱 | 3->OSX 系统语音
  noticeType: 0

  # Bark 通知配置
  bark:
    # Bark 端点地址
    barkServer: "https://api.day.app"
    # Bark Token
    barkToken: "<barkToken>"
    # 信息内容
    barkMessage: "【山姆助手】抢购成功，请及时付款！"
    # 提示音
    barkSound: "telegraph"

  # Server酱 通知配置
  ftqq:
    # Server酱 端点地址
    ftqqServer: "https://sctapi.ftqq.com"
    # 用户 Token，获取方式：https://sct.ftqq.com/sendkey
    ftqqSendKey: "<ftqqSendKey>"
    # 消息通道：最多支持两通道如："9|66"，具体通道请看 https://sct.ftqq.com/sendkey
    # 默认：方糖服务号
    ftqqChannel: "9"
    # 信息标题
    ftqqTitle: "【山姆助手】提醒"
    # 信息内容
    ftqqDesp: "抢购成功，请及时付款！"

  # OSX 系统语音配置
  sound:
    # 语音信息
    soundMessage: "山姆抢到啦 快去付款"
    # 重复播报次数
    soundTimes: 2
    # 播报声音
    soundVoice: "Ting-ting"
